### ISSUE TITLE
Feature request: Close modals on veil click

### ISSUE THREAD

**Issue by menosketiago** [OkunaOrg/okuna-web#100]
This one should be really minor but right now if you open a modal on a large screen you will need to move a lot to get the pointer on the close "button".

Unless a modal shows critical actionable information you can give the user the option to click on the "veil" to close it 🤓

**Comment by duichwer** [comment]
`Esc` does already work for keyboard users. :)

**Comment by starlesschris** [comment]
For me clicking on the veil does close it, but there are two little areas directly on the left and right where it does not (see the red boxes): 
![Screenshot_21](https://user-images.githubusercontent.com/22580809/92820277-120ce600-f3ca-11ea-89ce-768c57890cd6.png)
