### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by EdisonArango** [OkunaOrg/okuna-web#119]
Hi, 

I came across this project which may be helpful for a different project, I would like to contribute to this community so that we can push both projects forward, but I didn't find a LICENSE file for this repository, is there any particular reason for this?.

Thanks in advance.

**Comment by Mennaruuk** [comment]
I see AGPLv3 for the [website code](https://github.com/OkunaOrg/okuna-www/blob/master/LICENSE.txt), [API](https://github.com/OkunaOrg/okuna-api/blob/master/LICENSE), [API code](https://github.com/OkunaOrg/okuna-www-api/blob/master/LICENSE.txt), and [app](https://github.com/OkunaOrg/okuna-app/blob/master/LICENSE). The API wrapper, however, is [licensed ](https://github.com/OkunaOrg/okuna-js/blob/master/LICENSE)with the MIT license. And there is no license mentioned for okuna-web. So I think this there should be a license for it, I'm guessing Okula just hasn't gotten to it yet.

**Comment by jozsefsallai** [comment]
All Okuna components are now available under the MIT license.
