### ISSUE TITLE
Just a doubt 

### ISSUE THREAD

**Issue by jishnurajm** [OkunaOrg/okuna-web#144]
Why you people choose vue for website . You already have flutter, there is an option to build web in flutter . Then why you ppl not consider that

**Comment by jozsefsallai** [comment]
Many factors, some of which are:

- Flutter Web barely hit the stable channel earlier this year, it's still nowhere near production-ready yet
- The JavaScript ecosystem is much larger than the Flutter/Dart ecosystem
- Nuxt/Vue is a lot more mature and has established itself as a solid web framework
- Flutter Web is still currently bad in terms of things like SEO and server-side rendering; we would probably have to wait a few years until those things will become solid in Flutter Web
- (personally) I still think Flutter does an amazing job in the field of mobile apps ... but not so much in the web zone. There's many bugs and quirks to it and the resulting app doesn't really feel like a web application at all (for better or worse).

If Flutter Web matures enough and we see it worth using, then we might switch over to it in the future for Somus. But so far that is unlikely.

**Comment by jishnurajm** [comment]
Thank you brother for your well explained replay .I'm in waiting list for more than a year . Will you pls give me a invitation code to test your amazing orkuka 🙃

**Comment by jozsefsallai** [comment]
> Thank you brother for your well explained replay .I'm in waiting list for more than a year . Will you pls give me a invitation code to test your amazing orkuka 🙃

Okuna is no longer available, please see the details at https://www.okuna.io
