### ISSUE TITLE
Create modal with notice about the mobile version

### ISSUE THREAD

**Issue by lifenautjoe** [OkunaOrg/okuna-web#39]
Create a modal called OkWIP and display a message stating that the web version of Okuna is still in development and the functionality trying to be used has not yet being developed. 

Add two images with links to the Apple and Playstore mobile version downloads. 

We will call this modal whenever the user tries to click or do something that is not yet implemented.

Please create the modal in the same way we've created others. Using the ModalService and the OkModals component.

**Comment by jozsefsallai** [comment]
Some artwork/illustration would complement this well. Do you have any that we could use?
