### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by alsiPanda** [OkunaOrg/okuna-web#51]
I am getting a bunch of serializer related errors when trying to install dev and production build. Here is the screenshot:
![IMG_20200713_212744_265.jpg](https://user-images.githubusercontent.com/47055220/87326329-36764e80-c550-11ea-8342-1e7eeb86b48a.jpg)

Is this because the website is still under construction or something ?

**Comment by kitlu007** [comment]
Hi. I'm getting the same error ? @lifenautjoe could you help ?

**Comment by Komposten** [comment]
This was fixed in 36a483f. Can you pull latest master and try again?
