### ISSUE TITLE
Hashtag highlighting

### ISSUE THREAD

**Issue by flogruber** [OkunaOrg/okuna-web#83]
Not all hashtags are recognized correctly.  
Especially hashtags wird numbers and special characters.  

![image](https://user-images.githubusercontent.com/49080575/88941096-e1914280-d288-11ea-839d-77aa930a7a8b.png)
![image](https://user-images.githubusercontent.com/49080575/88941107-e7872380-d288-11ea-91e6-02fbb0335109.png)

I had a look at the [HashtagMatcher](https://github.com/OkunaOrg/okuna-web/blob/master/lib/matchers/HashtagMatcher.ts), which is used by OkSmartText, but the regex just works fine for all hashtags.  

It seems that the vue-text-highlight has a problem with numbers and special characters.

**Comment by Komposten** [comment]
Closing in favour of #96.
