### ISSUE TITLE
Hashtag regexp does not match the same as mobile

### ISSUE THREAD

**Issue by lifenautjoe** [OkunaOrg/okuna-web#96]

**Comment by lifenautjoe** [comment]
![image](https://user-images.githubusercontent.com/12737509/89452762-764ee100-d75e-11ea-8fd6-85bc2b37029d.png)

**Comment by Komposten** [comment]
Should be enough to change the HashtagMatcher's regex to `/\B#\w*[a-zA-Z]+\w*/`.
